import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  
  AppLocalizations(this.locale);
  
  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ?? 
           AppLocalizations(const Locale('es'));
  }
  
  static const LocalizationsDelegate<AppLocalizations> delegate = AppLocalizationsDelegate();
  
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // Textos generales
      'appTitle': 'GymScan',
      
      // Home Screen
      'scanButton': 'Scan Machine',
      'analyzing': 'Analyzing...',
      'uploadingImage': 'Uploading image...',
      'retrying': 'Retrying...',
      'errorCapturing': 'Error capturing image',
      'errorUploading': 'Error uploading image',
      'errorAnalyzing': 'Error analyzing image',
      'noConnection': 'No internet connection',
      'uploadingAttempt': 'Uploading... Attempt',
      'uploadSuccess': 'Successfully uploaded. Analyzing image...',
      'errorAfterAttempts': 'Error after attempts',
      'of': 'of',
      'capturing': 'Capturing...',
      'cameraPermissionRequired': 'Camera permission is required',
      'grantPermission': 'Grant permission',
      'cameraInitializing': 'Initializing camera...',
      'noInternet': 'No internet connection',
      'uploading': 'Uploading',
      'uploadedCorrectly': 'Successfully uploaded',
      'errorAfterRetries': 'Error after retries',
      'error': 'Error',
      'capture': 'Capture',
      
      // Machine Analysis Screen
      'mainMuscles': 'Main Muscles',
      'secondaryMuscles': 'Secondary Muscles',
      'instructions': 'Instructions',
      'backButton': 'Back to Camera',
      'noResults': 'No results available',
      'machineAnalysis': 'Machine Analysis',
      'machineName': 'Machine Name',
      'basicInstructions': 'Basic Usage Instructions',
      'detailedMachineInfo': 'Detailed information about the machine and its correct usage',
      'back': 'Back',
      
      // Splash Screen
      'loading': 'Loading...',
      'welcomeMessage': 'Welcome to GymScan',
      'appDescription': 'Identify gym machines and get exercise instructions',
      'identify_muscles': 'Identify the muscles you work',
      'loading_camera': 'Preparing camera...',
      
      // Info Dialog (Legal)
      'infoDialog_privacyTitle': 'Privacy Policy',
      'infoDialog_privacyText': '''Privacy Policy – GymScan
Last updated: April 2025
Responsible: GymScan

This Privacy Policy describes how the GymScan app collects, uses, and protects personal information you may provide when using the app. GymScan is committed to protecting the privacy of its users.

1. Information we collect

a) Non-personal information:
- Images captured to visually process gym machines.
- Device information (model, OS, language).
- Anonymous usage statistics.

b) Personal information:
GymScan does not collect sensitive personal information such as name, email, precise location, etc., unless explicitly required for future features like custom login.

2. Use of information
The information collected is used to:
- Process images using AI and generate exercise information.
- Improve functionality and user experience.
- Analyze usage metrics anonymously.

3. Storage and security
- Processed images are stored temporarily and are not shared with third parties without consent.
- We use secure services like Supabase for storage.
- We do not sell, share, or rent your information to third parties.

4. Advertising and analytics
GymScan may include ads via services such as Google AdMob. These services may use cookies or other identifiers to display personalized ads.

5. Permissions requested
The app requests the following permissions:
- Camera: to capture images of machines.
- Storage (if applicable): to temporarily save images.

6. Changes to this policy
We may update this Policy occasionally. Any changes will be posted on this page with the new date.

7. Contact
If you have questions, you can contact us at:
support@gymscan.app
''',
      'infoDialog_termsTitle': 'Terms and Conditions of Use',
      'infoDialog_termsText': '''Terms and Conditions of Use – GymScan
Last updated: April 2025

By using GymScan, you accept these terms. If you do not agree, you should not use the app.

1. Permitted use
GymScan is designed for users who want to obtain information about gym machines using AI. You may only use the app for personal, non-commercial purposes.

2. Generated content
The app generates informational content based on AI. This content is for guidance only and does not replace advice from a medical professional or certified trainer.

3. Liability
We are not responsible for injuries, errors, or misinterpretations resulting from the use of the app. Use of GymScan is at your own risk.

4. Intellectual property
All content, algorithms, images, and texts generated by GymScan are the property of the app creators or their respective owners.

5. Modifications
We may modify these terms at any time. By continuing to use the app after changes, you accept the new terms.

6. Suspension or cancellation
We reserve the right to suspend or restrict access to the app if misuse is detected.

7. Jurisdiction
This agreement is governed by the laws of Argentina.
''',
    },
    'es': {
      // Textos generales
      'appTitle': 'GymScan',
      
      // Home Screen
      'scanButton': 'Escanear Máquina',
      'analyzing': 'Analizando...',
      'uploadingImage': 'Subiendo imagen...',
      'retrying': 'Reintentando...',
      'errorCapturing': 'Error capturando imagen',
      'errorUploading': 'Error subiendo imagen',
      'errorAnalyzing': 'Error analizando imagen',
      'noConnection': 'Sin conexión a Internet',
      'uploadingAttempt': 'Subiendo... Intento',
      'uploadSuccess': 'Subido correctamente. Analizando imagen...',
      'errorAfterAttempts': 'Error después de intentos',
      'of': 'de',
      'capturing': 'Capturando...',
      'cameraPermissionRequired': 'Se requiere permiso de cámara',
      'grantPermission': 'Otorgar permiso',
      'cameraInitializing': 'Inicializando cámara...',
      'noInternet': 'Sin conexión a Internet',
      'uploading': 'Subiendo',
      'uploadedCorrectly': 'Subido correctamente',
      'errorAfterRetries': 'Error después de reintentos',
      'error': 'Error',
      'capture': 'Capturar',
      
      // Machine Analysis Screen
      'mainMuscles': 'Músculos principales',
      'secondaryMuscles': 'Músculos secundarios',
      'instructions': 'Instrucciones',
      'backButton': 'Volver a la Cámara',
      'noResults': 'No hay resultados disponibles',
      'machineAnalysis': 'Análisis de Máquina',
      'machineName': 'Nombre de la Máquina',
      'basicInstructions': 'Instrucciones básicas de uso',
      'detailedMachineInfo': 'Información detallada sobre la máquina y su uso correcto',
      'back': 'Volver',
      
      // Splash Screen
      'loading': 'Cargando...',
      'welcomeMessage': 'Bienvenido a GymScan',
      'appDescription': 'Identifica máquinas de gimnasio y obtén instrucciones de ejercicios',
      'identify_muscles': 'Identifica los músculos que trabajas',
      'loading_camera': 'Preparando cámara...',
      
      // Info Dialog (Legal)
      'infoDialog_privacyTitle': 'Política de Privacidad',
      'infoDialog_privacyText': '''Política de Privacidad – GymScan
Última actualización: abril 2025
Responsable: GymScan

Esta Política de Privacidad describe cómo la aplicación GymScan recopila, utiliza y protege la información personal que puedas proporcionar al utilizar la app. GymScan se compromete a proteger la privacidad de sus usuarios.

1. Información que recopilamos

a) Información no personal:
- Imágenes capturadas para procesar visualmente las máquinas de gimnasio.
- Información del dispositivo (modelo, sistema operativo, idioma).
- Estadísticas de uso anónimas.

b) Información personal:
GymScan no recopila información personal sensible, como nombre, correo electrónico, ubicación precisa, etc., a menos que explícitamente se solicite para funciones futuras como login personalizado.

2. Uso de la información
La información recopilada se utiliza para:
- Procesar imágenes mediante IA y generar información sobre ejercicios.
- Mejorar la funcionalidad y experiencia de usuario.
- Analizar métricas de uso de forma anónima.

3. Almacenamiento y seguridad
- Las imágenes procesadas se almacenan temporalmente y no se comparten con terceros sin consentimiento.
- Usamos servicios seguros como Supabase para manejar el almacenamiento.
- No vendemos, compartimos ni alquilamos tu información a terceros.

4. Publicidad y analítica
GymScan puede incluir anuncios mediante servicios como Google AdMob. Estos servicios pueden usar cookies u otros identificadores para mostrar anuncios personalizados.

5. Permisos solicitados
La app solicita los siguientes permisos:
- Cámara: para capturar imágenes de las máquinas.
- Almacenamiento (si aplica): para guardar temporalmente las imágenes.

6. Cambios en esta política
Podemos actualizar esta Política ocasionalmente. Cualquier cambio será publicado en esta misma página con la nueva fecha.

7. Contacto
Si tienes preguntas, puedes contactarnos a:
support@gymscan.app
''',
      'infoDialog_termsTitle': 'Términos y Condiciones de Uso',
      'infoDialog_termsText': '''Términos y Condiciones de Uso – GymScan
Última actualización: abril 2025

Al usar GymScan, aceptas estos términos. Si no estás de acuerdo, no deberías usar la aplicación.

1. Uso permitido
GymScan está diseñado para usuarios que deseen obtener información sobre máquinas de gimnasio mediante IA. Solo puedes usar la app con fines personales y no comerciales.

2. Contenido generado
La app genera contenido informativo basado en IA. Este contenido es orientativo y no sustituye el asesoramiento de un profesional médico o entrenador certificado.

3. Responsabilidad
No nos responsabilizamos por lesiones, errores o malinterpretaciones derivados del uso de la app. El uso de GymScan es bajo tu propio riesgo.

4. Propiedad intelectual
Todos los contenidos, algoritmos, imágenes y textos generados por GymScan son propiedad de los creadores de la app o sus respectivos titulares.

5. Modificaciones
Podemos modificar estos términos en cualquier momento. Al seguir usando la app después de los cambios, aceptas los nuevos términos.

6. Suspensión o cancelación
Nos reservamos el derecho de suspender o restringir el acceso a la app si se detecta un uso indebido.

7. Jurisdicción
Este acuerdo se rige por las leyes de Argentina.
''',
    },
  };
  
  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? 
           _localizedValues['es']?[key] ?? 
           key;
  }
  
  // Getters para acceder directamente a las traducciones
  String get analyzing => get('analyzing');
  String get cameraPermissionRequired => get('cameraPermissionRequired');
  String get grantPermission => get('grantPermission');
  String get machineName => get('machineName');
  String get mainMuscles => get('mainMuscles');
  String get secondaryMuscles => get('secondaryMuscles');
  String get basicInstructions => get('basicInstructions');
  String get machineAnalysis => get('machineAnalysis');
  String get detailedMachineInfo => get('detailedMachineInfo');
  String get back => get('back');
  String get noInternet => get('noInternet');
  String get uploading => get('uploading');
  String get uploadedCorrectly => get('uploadedCorrectly');
  String get errorAfterRetries => get('errorAfterRetries');
  String get error => get('error');
  String get capture => get('capture');
  String get infoDialog_privacyTitle => get('infoDialog_privacyTitle');
  String get infoDialog_privacyText => get('infoDialog_privacyText');
  String get infoDialog_termsTitle => get('infoDialog_termsTitle');
  String get infoDialog_termsText => get('infoDialog_termsText');
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();
  
  @override
  bool isSupported(Locale locale) {
    return ['en', 'es'].contains(locale.languageCode);
  }
  
  @override
  Future<AppLocalizations> load(Locale locale) {
    return Future.value(AppLocalizations(locale));
  }
  
  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
